### ISSUE TITLE
gridsome build fails with error: Cannot read property 'undetermined' of null

### ISSUE THREAD

**Issue by goodhands** [goodhands/goodhands.github.io#17]
I get the output below when I run `npm run deploy`, which runs `gridsome build` under the hood.

The error seems to emanate from `purgecss`'s extractors (can't figure out which content type is unsupported as it supports `.md` files by default) and began after working on the blog features #16 
````
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'undetermined' of null
    at g.merge (C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\purgecss\lib\purgecss.js:1:2228)   
    at new g (C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\purgecss\lib\purgecss.js:1:1961)     
    at b (C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\purgecss\lib\purgecss.js:1:3497)
    at async U.extractSelectorsFromFiles (C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\purgecss\lib\purgecss.js:1:5545)
    at async C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\@fullhuman\postcss-purgecss\lib\postcss-purgecss.js:1:571
    at C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\loader-runner\lib\LoaderRunner.js:367:11    
    at C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\loader-runner\lib\LoaderRunner.js:233:18    
    at context.callback (C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\HP\Documents\Code\sites\goodhands.github.io\node_modules\postcss-loader\src\index.js:208:9
````

**Comment by goodhands** [comment]
Ah silly error message caused by any empty file in the `./src` path.

Thanks to this [post](https://community.netlify.com/t/gridsome-build-fails-yep-checked-the-other-posts/20892)
